FROM dockercore/iso

RUN { \
		echo 'VARIANT="VMware"'; \
		echo 'VARIANT_ID=vmware'; \
	} >> /etc/os-release

RUN apt-get update && apt-get install -y --no-install-recommends \
		$(dpkg-query --show --showformat='${Package}\n' | awk '/^linux-image-[0-9]/ { gsub(/-image-/, "-headers-"); print }') \
		\
		open-vm-tools \
		open-vm-tools-dkms \
	&& rm -rf /var/lib/apt/lists/*
