#!/bin/sh
set -e

### BEGIN INIT INFO
# Provides:          boot2docker-hooks-after-docker
# Required-Start:    $remote_fs docker
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: boot2docker hooks: after-docker
# Description:       Run scripts from /etc/boot2docker/hooks/after-docker.d
#                    after Docker starts up.
### END INIT INFO

. /lib/lsb/init-functions

case "$1" in
	start|restart|reload|force-reload)
		for hook in /etc/boot2docker/hooks/after-docker.d/*.sh; do
			if [ -x "$hook" ]; then
				"$hook"
			fi
		done
		exit 0
		;;
	stop|status)
		exit 0
		;;
esac
